# -*- coding: utf-8 -*-
"""Colaborativo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RERXyFFBjmzBmcD6Myt1AyPgfZcR8zS8
"""

iProgram = 'n'

print("Bienvenido al sistema de información de txtsas desea iniciar el programa S/N")

iProgram=input().lower()

gen=["Nombre","T.asignado","T.promedio","Eficiencia","ltsag","P.distrib.","lts desp","nvCumDesp","Tasa entrega"]
listaCamiones = []

def agregarcamion(nombrecamion,nompDis,ltsag):
  camion=[nombrecamion,0,0,0,ltsag,nompDis,0,0,0]
  listaCamiones.append(camion)

def asignardespacho(nombrecamion,tiempo):

  for i in range(len(listaCamiones)):
      if listaCamiones[i][0]==nombrecamion:
        listaCamiones[i][1]=tiempo


def registrardespacho(nombrecamion,tiempo,lts):

    for i in range(len(listaCamiones)):
      if listaCamiones[i][0]==nombrecamion:
        if listaCamiones[i][2]==0:
           listaCamiones[i][2]=tiempo
           listaCamiones[i][6]=lts
        else:
          suma=(int(listaCamiones[i][2]+tiempo))/2
          listaCamiones[i][2]=suma
          suma=(int(listaCamiones[i][6]+lts))/2
          listaCamiones[i][6]=suma


def validareficiencia():
    for i in range(len(listaCamiones)):
      if listaCamiones[i][2]==0:
         listaCamiones[i][3]=0
         listaCamiones[i][6]=0
         listaCamiones[i][7]=0
      else:
#Eficiencia en tiempos de despacho = (Tiempo de despacho registrado) / Tiempo de despacho asignado x 100
          listaCamiones[i][3]=round(listaCamiones[i][2]/listaCamiones[i][1]*100,2)

#Nivel de Cumplimiento de los despachos = Litros despachados / Total de litros asignados x 100
          listaCamiones[i][7]=round(listaCamiones[i][6]/listaCamiones[i][4]*100,2)

#Tasa de entrega (Lt/min) = Cantidad de litros despachados / Tiempo total de despacho
          listaCamiones[i][8]=round(listaCamiones[i][6]/listaCamiones[i][2]*100,2)

    print("por favor ingrese estandar")
    estand=int(input())
    print(gen)
    total=''
    print(listaCamiones)
    print(f"estandar min {estand} %")
    for i in range(len(listaCamiones)):
      if listaCamiones[i][3]<estand:
         total= total+(f"el camion esta {listaCamiones[i][0]} fuera del estandar\n")
    print(total)





while iProgram =='s':

  print("elija la opcion que desea realizar:\n 1. agregar camion\n 2. asignar despacho\n 3. registrar despacho\n 4. validar eficiencia\n")

  option=int(input())

  if option==1:
    print("digite el nombre del camion, el punto de distribución,  el tiempo de despacho y litros asignados")
    nomcam=input().split()


    agregarcamion(nomcam[0],nomcam[1],int(nomcam[3]))
    tdespacho=int(nomcam[2])
    asignardespacho(nomcam[0],tdespacho)

  elif option==2:
    print("digite el nombre del camion")
    nomcam=input()

    print("digite el tiempo de despacho asignado")
    tdespacho=int(input())

    asignardespacho(nomcam,tdespacho)

  elif option==3:
    print("digite el nombre del camion, tiempo de despacho real y litros despachados")
    nomcam=input().split()
    registrardespacho(nomcam[0],int(nomcam[1]),int(nomcam[2]))

  elif option==4:
    validareficiencia()

  else:
    print("opcion no valida\n\n")

    print("Hola")


print("El sistema no fue iniciado")