# -*- coding: utf-8 -*-
"""7_Manejo_de_archivos_texto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xK7QqHBAjQsI-4Pqk_zjPpC4ppvW8Mc8

#**MANEJO DE ARCHIVOS DE TEXTO CON PYTHON**

Antes de poder realizar cualquier operación de lectura/escritura hay que abrir el archivo con **open()** indicando su ubicación y nombre seguido, opcionalmente, por el modo o tipo de operación a realizar y la codificación que tendrá el archivo.

Si no se indica el tipo de operación el archivo se abrirá en modo de lectura y si se omite la codificación se utilizará la codificación actual del sistema.

Si no existe la ruta del archivo o se intenta abrir para lectura un archivo inexistente se producirá una excepción del tipo IOerror.


###**MODOS DE APERTURA**

**r = lectura**
**a = append**
**w = escritura**
"""

import locale
print(locale.getpreferredencoding())


# Apertura de un archivo con open()

file = open('el_quijote - copia.txt',mode='r')
contenido = file.read()
print(type(contenido))
print(len(contenido))
print(contenido)
file.close()

"""###**APERTURA CON WITH - AS**"""

with open('el_quijote - copia.txt') as elquijote:
  print(elquijote.read())

from google.colab import files
files.upload()

# LUEGO DE SUBIR EL QUIJOTE VAMOS A LEER EL ARCHIVO
with open('el_quijote_edited.txt') as ar:
  print(ar.read())

"""###**LECTURA DE UN ARCHIVO**"""

# LEER UNA LINEA DEL ARCHIVO DE TEXTO

with open('el_quijote - copia.txt') as quijote:
  print(quijote.readline())
  print(quijote.readline())
  print(quijote.readline())
  print(quijote.readline())
  print(quijote.readline())
  print(quijote.readline())

# LEER TODAS LAS LINEAS CON readline()
with open('el_quijote - copia.txt') as quijote:
  while(True):
    linea = quijote.readline()
    print(linea)
    if not linea:
      print('Terminó la lectura del archivo')
      break

# LEER TODAS LAS LINEAS CON readlines()
l = []
with open('el_quijote - copia.txt') as quijote:
  linea = quijote.readlines()
  print(linea)

  for i in linea:
    l.append(i.rstrip("\n"))
print(l)



"""###**ESCRITURA DE UN ARCHIVO**"""

from google.colab import files
files.upload()

# ESCRITURA DEL ARCHIVO CON 'W'  -- SOBREESCRIBE EL CONTENIDO DEL ARCHIVO
with open('archivo2.txt', 'w') as quijote:
  linea2 = 'Esta es la segunda línea del archivo \nY esta es la tercera línea'
  quijote.write(linea2)
quijote.close()

with open('archivo2.txt', "w") as quijote:
  linea = "Esta es la última linea de verdad verdad"
  quijote.write(linea)
  #linea = quijote.readlines()
quijote.close()

# ESCRITURA DEL ARCHIVO CON 'a'  -- AGREGA INFORMACIÓN AL FINAL DEL ARCHIVO CONSERVANDO LO INICIAL
with open('archivo2.txt', 'a') as quijote:
  linea_nueva = '\nEsta es un linea adicionada \nY acá también hay otra más, y \nesta es la última de verdad'
  quijote.write(linea_nueva)
quijote.close()

with open('archivo2.txt') as quijote:
  linea = quijote.readlines()
  print(linea)
  linea.pop(1)
  print(linea)
quijote.close()

with open('archivo2.txt', 'w') as quijote:
  nuevo_contenido = ",".join(linea)
  print("Nuevo", nuevo_contenido)
  quijote.write(nuevo_contenido)
quijote.close()

# DESGLOSE DE ELEMENTOS DEL ARCHIVO, RECOLECTADOS CON readlines()

with open('el_quijote - copia.txt') as quijote:
  all_lines = quijote.readlines()

for line in all_lines:
  print(line)
  for valor in line:
    print(valor)
quijote.close()