# -*- coding: utf-8 -*-
"""8_Excepciones_(manejo_de_errores).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vRBACDklca4kRAtsTWA3hE4AHPkI6GVE

#**MANEJO DE EXCEPCIONES O ERRORES**

Las excepciones o errores que se pueden producir durante la ejecución de un programa Python se gestionan con una construcción **try-except**.

Una excepción puede ocurrir cuando:


*   Se operan datos de distinto tipo.
*   División por cero.
*   Ingreso de un tipo de dato no esperado.
*   Acceso a un archivo inexistente.
*   Otras situaciones previsibles.

El control de los errores con el manejo de excepciones permite evitar que un programa suspenda su ejecución de manera inesperada.

###**TRY - CATCH**

try:     # contiene el código que puede producir la excepción

except:  # contiene el código que gestionará cualquier error

except TipoError:  # contiene el código que gestionará un tipo de error concreto

else:    # contiene el código que se ejecutará en caso de no haber error

finally: # contiene el código que se ejecutará en cualquier caso.
"""

# Ejemplo de aplicación de try - except

try:
    file = open("miarchivito.txt")


except:
    print("Hay un problema con la apertura del archivo")

finally:
  print("Fin del programa")

# Ejemplo de división por cero
# a = 5/0

# Ejemplo de ingreso de tipo de dato no esperado
# dato = 5
# print('El dato introducido es {%s}'.format(dato))

# Operación de datos de diferente tipo
# a = 100.8
# b = '87'
# producto = a * b
# print(producto)

# NOMBRES DE ERRORES MÁS COMUNES
#ZeroDivisionError
#KeyError
#TypeError



# Es    cribir una función que calcule el total de una factura tras
# aplicarle el IVA.
# La función debe recibir la cantidad sin IVA y el porcentaje de
# IVA a aplicar, y devolver el total de la factura.
# Si se invoca la función sin pasarle el porcentaje de IVA,
# deberá aplicar un 21%.

def total_Factura(cantidad_factura = 0, procentaje_Iva = 21 ):
    porcentaje = procentaje_Iva / 100
    iva = cantidad_factura * porcentaje
    total = cantidad_factura + iva
    return total

try:
    cantidad_factura = int(input("Ingrese el cantidad de su factura: "))
    num_iva = int(input("Ingrese el iva sin el signo'%': "))

except :
    num_iva = 21
    solucion = total_Factura(cantidad_factura, num_iva)
    print(f"El total de la factura es: {int(solucion)}")
else:
    solucion = total_Factura(cantidad_factura, num_iva)
    print(f"El total de la factura es: {int(solucion)}")